version: "3"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    restart: always

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - database
    restart: always
